# Используем Node.js LTS (в т.ч. 22)
FROM node:22-slim

# Рабочая директория внутри контейнера
WORKDIR /app

# Копируем зависимости
COPY package*.json ./

# Устанавливаем зависимости (npm ci — быстрее и чище)
RUN npm ci

# Копируем оставшиеся файлы
COPY . .

# Открываем порт, на котором работает React dev server
EXPOSE 3000

# Запуск команды разработки
CMD ["npm", "start"]
