name: Deploy React App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: SSH into server, deploy configs
      run: |
        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e

          cd /root/WebAppKubSU
          git pull origin master

          echo "Stopping and removing old container..."
          docker stop webappkubsu || true
          docker rm webappkubsu || true

          echo "Rebuilding image..."
          docker build -t webappkubsu .

          echo "Running container with name..."
          docker run -d --name webappkubsu -p 3003:80 webappkubsu

          echo "✅ Деплой завершён успешно"
        EOF
