name: Deploy Nginx

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: SSH into server, deploy configs, reload Nginx
      run: |
        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e

          cd /home/${{ secrets.SSH_USER }}/WebAppKubSU
          git pull origin master
          
          docker stop webappkubsu
          docker rm webappkubsu
          docker build -t webappkubsu .
          docker run -d -p 3003:80 webappkubsu

          # Проверяем конфигурацию
          sudo nginx -t

          # Применяем изменения
          sudo systemctl reload nginx

          echo "Конфигурация обновлена и Nginx перезагружен"
        EOF